name: Sync labels
on:
  # You can run this with every type of event, but it's better to run it only when you actually need it.
  workflow_dispatch:

  push:
    # Only run on pushes to the 'main' branch
    branches:
      - "main"
    # Only run if the specified file(s) are changed
    paths:
      - ".github/labels.yml"

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          config-file: .github/labels.yml

          # If you want to delete any additional label, set this to true
          delete-other-labels: true

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false
